MERCURY_ART = <<-'EOF'


M"""""`'"""`YMMM""""""""`MMM"""""""`MMMM'""""'YMMM""MMMMM""MMM"""""""`MMM""MMMM""M
M  mm.  mm.  MMM  mmmmmmmMMM  mmmm,  MM' .mmm. `MM  MMMMM  MMM  mmmm,  MM. `MM' .M
M  MMM  MMM  MM`      MMMMM'        .MM  MMMMMooMM  MMMMM  MM'        .MMM.    .MM
M  MMM  MMM  MMM  MMMMMMMMMM  MMMb. "MM  MMMMMMMMM  MMMMM  MMM  MMMb. "MMMMb  dMMM
M  MMM  MMM  MMM  MMMMMMMMMM  MMMMM  MM. `MMM' .MM  `MMM'  MMM  MMMMM  MMMMM  MMMM
M  MMM  MMM  MMM        .MMM  MMMMM  MMM.     .dMMb       dMMM  MMMMM  MMMMM  MMMM
MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

EOF
