MEANINGS = {
  Aries: {
    Sun: "Aries is an active, energetic sign. People with Sun in Aries are direct, straightforward, and uncomplicated. They expect the same from others, and are baffled when they don’t always get it.",
    Moon: "They live in the moment and have a hard time waiting for things to happen. Whims of the moment take absolute precedence in their lives.",
    Mercury: "Mercury in Aries communicators make quick decisions–so quick that you might think they don’t much like thinking things over. The truth is, Aries communicators don’t have a lot of patience for mulling. Their decisions are often driven by the need for instant gratification.",
    Venus: "Venus in Aries people flirt by being up-front, direct, and even daring. They try to win you over by expressing how enterprising and independent they are.",
    Mars: "This is a very impulsive position of Mars. The first instinct for Mars in Aries natives is to take action. Quick flare-ups characterize the Mars in Aries character, but their anger usually doesn’t last for too long.",
    },
  Taurus: {
    Sun: "Taurus natives are sensual folk–and this includes sex, but extends to pleasures in all areas: they delight in the sensual pleasures of food, a comfortable blanket, a richly colored aquarium to look at, the smell of flowers or spring rain, pleasing melodies coming from their stereos, and so forth. Though they are dependable most of the time, this generally shows itself more in habit than in outright helpfulness.",
    Moon: "Familiarity is important to Lunar Taureans. These people are earthy and strong-willed. They feel with their senses and they are pretty much rooted in their ways.",
    Mercury: "Mercury in Taurus natives are plodders. They may take their time to arrive at a decision, but they get there — they are actually quite decisive, even stubborn with their opinions.",
    Venus: "Love for Venus in Taurus centers on the physical world and creature comforts — they revel in sensual surroundings. These people project themselves as solid and comfortable.",
    Mars: "“Slow and steady wins the race” could easily be a motto for Mars in Taurus. These goal-oriented people are not known for their speed, but their staying power is tremendous.",
  },
  Gemini: {
    Sun: "With the Sun in Gemini, the urge for self-expression is strong. These natives are often just as interested in collecting information as they are in sharing it. Curious to a fault, Geminis have a finger in every pie. ",
    Moon: "Lunar Geminis are usually pleasant, witty, and charming people. At home and with family, however, they can be moody and irritable at times.",
    Mercury: "Mercury in Gemini people are generally quick-witted. They can come across as somewhat scattered, and this is mainly due to their eclectic interests. They seem to know a little about everything.",
    Venus: "Venus in Gemini people will try to win over the object of their affection with witty conversation, displaying just how much they “know”, and demonstrating their diverse interests. These lovers are playful — some might even call them a tease.",
    Mars: "When Mars in Gemini natives get angry or fired up, they use words as their “weapon”. Angry words–some of the most incisive and sarcastic ones–can fly around with the more energetic natives.",
  },
  Cancer: {
    Sun: "Sun in Cancer natives have a strong survival instinct. They are protective of those they care about, and of themselves too. They are often quite reticent about sharing their inner selves with the rest of the world, and are often caught up in reminisce.",
    Moon: "Moon in Cancer people are never detached — they cling to things, their home, and people they care for. They seek out security and familiarity in all they do. They look for peace and quiet.",
    Mercury: "These people communicate with feeling, conveying a sensitive, withdrawn, and thoughtful nature to the people they interact with. If this is the only personal planet in Cancer in their chart, they may come across as more personal and sensitive than they actually are.",
    Venus: "Love for Venus in Cancer is best when it is committed and rather predictable. These people are sensitive in love, even if their Sun sign is the more playful and outgoing signs of Gemini or Leo.",
    Mars: "This position inclines toward passive-aggressiveness. These people seem to resist change and to shy away from direct confrontations. They need to feel secure before they act.",
  },
  Leo: {
    Sun: "There’s an unmistakably regal air to Solar Leos. These are dignified–even noble–folk. Leos have a reputation for being conceited, but think again. Leos do feel important, but this generally takes the form of wanting to change the world in some way–to make the world a better place. They are generally motivated by affection for people.",
    Moon: "Lunar Leos often feel a need to organize, and even control, their families and friends. They have an inner mission to set things right, and generally like to oversee the goings-on in their little circle.",
    Mercury: "When Mercury in Leo people speak, they do it with authority. Some of them come across as know-it-alls, but the more mature ones speak with style. They want others to know about their presence of mind and their know-how.",
    Venus: "Venus in Leo loves to court and be courted, and they need to feel very special. They are warm, generous, and even grand. Though really quite loyal to their partners (remember that love is THE most important thing in Leo’s life), they thrive on romantic attention.",
    Mars: "This position of Mars gives a drive for significance. Mars in Leo individuals possess a strong need to create in some wayand they are determined that their lives  have not only meaning, but significant meaning!",
  },
  Virgo: {
    Sun: "Virgo people are generally respectable, hard-working individuals who have a love of knowledge and know-how.Virgo’s symbol, the Virgin, shows itself in the lives of Virgos through a love of all that is “natural” and a certain purity of spirit that keeps Virgos self-sufficient and self-contained, at least on the surface.",
    Moon: "Lunar Virgos find security in the little things in life. They feel most content when they’ve straightened out all the details of everyday life.",
    Mercury: "Mercury in Virgo people are rarely flashy in their communication style, but they do thoroughly appreciate it when others acknowledge their brainpower. These people love to keep track of all the details.",
    Venus: "Venus in Virgo people are not the flirtatious sort. Instead, their appeal lies in their dedication, their willingness to work on the relationship, and to make the relationship work in real terms.",
    Mars: "Most Mars in Virgo natives are not particularly aggressive by nature. Although they can be a little hard-nosed and critical at times, they rarely resort to pushing others around. Still, an annoyed Mars in Virgo native can be difficult to be around!",
  },
  Libra: {
    Moon: "Moon in Libra people have a strong need for partnership. Without someone to share their lives with, they feel utterly incomplete. This is why many people with this position get involved in marriages or living-together arrangements quite young.",
    Mercury: "Libra communicators come across as very pleasing. Diplomacy comes naturally to these natives. At the very least, they take many pains to be diplomatic.",
    Venus: "Venus in Libra people will try to impress you with their kindness, evenhandedness, and willingness to make your relationship work. They have a polished manner in love, which sometimes makes them appear insincere or superficial. They are gentle lovers who hate to be offended.",
    Mars: "Mars in Libra natives often reflect about things before they act. Decisiveness is not their strong point, but they do, eventually, get things done. Many people with this position procrastinate, generally because they feel the need to weigh all of the alternatives before taking action.",
  },
  Scorpio: {
    Moon: "While others may find security and comfort in material things, Moon in Scorpio people seek out emotional intensity. No matter what, there is something very intense about Lunar Scorpios. Their ability to see what isn’t obvious to the rest of the world can be intimidating or wildly attractive, depending on the audience.",
    Mercury: "These people are on an eternal quest to get to the very heart of any matter. This appears in anything that requires thought, and in almost every conversation they have.",
    Venus: "Venus in Scorpio people attract others with their intensity and willingness to commit. They have a strong and concentrated manner which suggests their feelings run deep. Their actions in love tend to promise deep commitment and sexual pleasure, even if they are not telling you this directly.",
    Mars: "Mars in Scorpio natives love to challenge themselves to do the impossible. They throw themselves into what they decide to do with concentrated energy and awesome willpower.",
  },
  Sagittarius: {
    Moon: "More than anything, Lunar Sagittarians have a need for personal freedom and space. They are extraordinarily happy and easygoing folk, as long as they don’t feel caged in or cooped up.",
    Mercury: "Freedom of thought is what Mercury in Sagittarius strives for — at least in theory. These people communicate in an optimistic, forward-looking manner. Their ideas are generally very big, but it’s probably wise to use tact when you see all the little holes in their arguments.",
    Venus: "When Venus in Sagittarius people are in love, they need to feel they can grow and expand their horizons through their relationship. They want to learn new things, and experience everything together. These are idealistic lovers who want you to appreciate their beliefs, visions, and ideals.",
    Mars: "When Mars in Sagittarius people get angry, they feel like running. They have to do something–not about it, but something else altogether. They don’t have a lot of patience to wait things out.",
  },
  Capricorn: {
    Moon: "Being useful and productive are basic needs for Lunar Capricorns. Because they generally keep their emotions under check, Moon in Capricorn people come across as competent people.",
    Mercury: "With Mercury in Capricorn, natives have a strong need to compartmentalize the impressions they get from the world. These people often speak and write in a slow and methodical manner. They appreciate structure and order.",
    Venus: "Venus in Capricorn people will try to win your heart by displaying self-control, presence of mind, and responsible behavior. These lovers want you to know they are goal-oriented, witty, savvy, and controlled. Nobody can get the best of them.",
    Mars: "With fiery Mars in the more orderly sign of Capricorn, natives with this position have a subdued and controlled style of approaching life. Most don’t come across as particularly enthusiastic; rather, theirs is a low-key but determined energy.",
  },
  Aquarius: {
    Moon: "Moon in Aquarius people are extremely observant. They are lifetime students of human nature, loving to analyze why people do what they do. This often stems from a detached–even shy–personality, especially in youth.",
    Mercury: "Unconventional in self-expression, Mercury in Aquarius natives enjoy breaking the rules. They are not necessarily loud or flamboyant people, but they often have a quiet way of stirring others up. These natives delight in exposing what they deem biases in others’ way of thinking.",
    Venus: "Venus in Aquarius people try to impress you with their open-minded, future-thinking spirit. They want you to see them as unique, rebellious, and a little provocative. They are attractive when they are acting a little aloof.",
    Mars: "The tried-and-true methods of getting things done are far too boring for those born with Mars in this unique and original sign. Mars in Aquarius natives often have a rather original view of the world as well.",
  },
  Pisces: {
    Moon: "Lunar Pisceans are known to be dreamy and not always in touch with reality. However, though these people may not always show real-world savvy in day-to-day, practical affairs, they make up for this with remarkable intuition.",
    Mercury: "Mercury in Pisces are gentle communicators with a soft touch that is pleasing and warm. Some of them come across in an almost poetic way. Not given to bother too much with details, these individuals tend to sponge up the feelings and moods of their environment.",
    Venus: "Venus in Pisces people project themselves as dreamy, soft-hearted partners. Everything about the way they flirt promises a lovely time. Theirs is an elusive charm — they are sweetly playful, a little moody, and perhaps a little irregular.",
    Mars: "Mild-tempered and gentle, these guys and gals move through life in a manner that can hardly be considered direct. Mars is the planet of action and assertion, and Pisces is a passive sign that rarely asserts itself in a direct fashion.",
  }
}
