MEANINGS = {
  Aries: {
    Sun: "Aries is an active, energetic sign. People with Sun in Aries are direct, \nstraightforward, and uncomplicated. They expect the same from others, \nand are baffled when they don’t always get it.",
    Moon: "They live in the moment and have a hard time waiting for things to happen. \nWhims of the moment take absolute precedence in their lives.",
    Mercury: "Mercury in Aries communicators make quick decisions–so quick that you might think they don’t much like thinking things over. The truth is, Aries \ncommunicators don’t have a lot of patience for mulling. \nTheir decisions are often driven by the need for instant gratification.",
    Venus: "Venus in Aries people flirt by being up-front, direct, and even daring. \nThey try to win you over by expressing how enterprising and independent \nthey are.",
    Mars: "This is a very impulsive position of Mars. The first instinct for Mars in \nAries natives is to take action. Quick flare-ups characterize the Mars \nin Aries character, but their anger usually doesn’t last for too long.",
    Uranus: "People with a Uranus in Aries placement search for what is new and out of \nthe ordinary, but are prone to foolhardiness and can be extremely eccentric.",
    Jupiter: "There's a belief in the power of positivity, that life is what you make of it. \nLoves competition, doing things independently. Values instant results. \nAttracts the most good fortune when he/she takes the lead, initiates, inspires, and demonstrates enthusiasm and courage.",
    Saturn: "While Saturn in Aries may cause a delayed development of ambition in their life, \nthey may end up taking on a lot of responsibility when still very young. \nObstacles arise that may block progress. Having to assert \nthemselves can cause a lot of anxiety. Anger may be an issue, \nalthough others see them as controlled and cool the majority of the time."
    },
  Taurus: {
    Sun: "Taurus natives are sensual folk–and this includes sex, but extends to pleasures in \nall areas: they delight in the sensual pleasures of food, a comfortable blanket, \na richly colored aquarium to look at, the smell of flowers or spring rain, \npleasing melodies coming from their stereos, and so forth. Though they are dependable \nmost of the time, this generally shows itself more in habit than in outright helpfulness.",
    Moon: "Familiarity is important to Lunar Taureans. These people are earthy and strong-willed. \nThey feel with their senses and they are pretty much rooted in their ways.",
    Mercury: "Mercury in Taurus natives are plodders. They may take their time to arrive at a decision, \nbut they get there — they are actually quite decisive, even stubborn with their opinions.",
    Venus: "Love for Venus in Taurus centers on the physical world and creature comforts — they revel \nin sensual surroundings. These people project themselves as solid and comfortable.",
    Mars: "“Slow and steady wins the race” could easily be a motto for Mars in Taurus. These goal-oriented \npeople are not known for their speed, but their staying power is tremendous.",
    Uranus: "There is a clash here between oppising tendencies. Fixed Taurus wants to sit still while \nUranus wants to break free from all conventions. A person with this placement is stubborn and brilliant.",
    Jupiter: "There is a delight in sensual pleasures and wants the good life. A strong feeling of what they \nwant is worth attracts success. Good instincts for finances, \nwhat things are worth/good products, and investing. Attracts the most good fortune when \nhe/she is charitable, generous but discriminating, and patient. Watch for over-indulgence.",
    Saturn: "Saturn in Taurus has a deep need to feel secure; both emotionally and financially. \nThey like to keep a strict control over their daily tasks. Unfortunately for them, \nnothing comes easy. They have to work hard for everything they get."
  },
  Gemini: {
    Sun: "With the Sun in Gemini, the urge for self-expression is strong. These natives are often just \nas interested in collecting information as they are in sharing it. \nCurious to a fault, Geminis have a finger in every pie. ",
    Moon: "Lunar Geminis are usually pleasant, witty, and charming people. At home and with family, however, \nthey can be moody and irritable at times.",
    Mercury: "Mercury in Gemini people are generally quick-witted. They can come across as somewhat scattered, \nand this is mainly due to their eclectic interests. They seem \nto know a little about everything.",
    Venus: "Venus in Gemini people will try to win over the object of their affection with witty conversation, \ndisplaying just how much they “know”, and demonstrating their diverse interests. These lovers are playful — some might even call them a tease.",
    Mars: "When Mars in Gemini natives get angry or fired up, they use words as their “weapon”. Angry words–some \nof the most incisive and sarcastic ones–can fly around \nwith the more energetic natives.",
    Uranus: "Brimming with original ideas, Uranus in Gemini is great at creating and carrying out work, but can voccasionally become restless.",
    Jupiter: "There is an attraction to good fortune if a person with this placement uses their wit and ingeniousness, \nis versatile, sociable, curious, and puts others at \nease with friendliness and sincere curiosity. Values the intellect \nand sees opportunities to grow and succeed through intellectual, verbal, and written channels. Believes that intelligence and knowledge are the keys to solving problems.",
    Saturn: "Saturn in Gemini can adapt to different situations easily, using a systematic and logical approach. \nThey are cool and rational in the face of adversity. \nThey have excellent powers of reasoning, so they do well in mathematics and science."
  },
  Cancer: {
    Sun: "Sun in Cancer natives have a strong survival instinct. They are protective of those they care about, and of themselves too. They are often quite reticent about sharing their inner selves with the rest of the world, and are often caught up in reminisce.",
    Moon: "Moon in Cancer people are never detached — they cling to things, their home, and people they care for. They seek out security and familiarity in all they do. They look for peace and quiet.",
    Mercury: "These people communicate with feeling, conveying a sensitive, withdrawn, and thoughtful nature to the people they interact with. If this is the only personal planet in Cancer in their chart, they may come across as more personal and sensitive than they actually are.",
    Venus: "Love for Venus in Cancer is best when it is committed and rather predictable. These people are sensitive in love, even if their Sun sign is the more playful and outgoing signs of Gemini or Leo.",
    Mars: "This position inclines toward passive-aggressiveness. These people seem to resist change and to shy away from direct confrontations. They need to feel secure before they act.",
    Uranus: "Cancers moodiness combined with the unpredictability of Uranus sometimes causes problems. The imagination is enhanced, but not always certain of what it wants.",
    Jupiter: "This placement encourages sympathy, and promotes the ability to comforts other. Values tradition and works towards security. Relies most on gut instincts when it comes to pursuing goals and business success.",
    Saturn: "Saturn in Cancer is not very emotionally demonstrative. They prefer to hide their inner thoughts and feelings. Home and family is of utmost importance. They often give up other opportunities to take care of their family. They often have a strong bond with their family members, though they have trouble expressing it. Life lessons include learning to feel empathy and the value of responsibility."
  },
  Leo: {
    Uranus: "Incred energy and boldness makes anyone with this placement extremely confident with a power-hungry streak.",
    Pluto: "Pluto stays in a sign for 14-30 years, meaning its effects are generational like Uranus and Neptune. When Pluto is in Leo, the goal is transformation towards actualization.",
    Jupiter: "This placement understands that generosity brings success. There is a magnanimity and generosity that inspires others to act with dignity and sincerity.",
    Saturn: "Leo Saturn can undermine their goals by undervaluing themselves. This attitude of inferiority can sabotage all they work towards. Their feelings of jealousy and lack of spontaneity can push others away. They often put up a coldness towards others to protect themselves emotionally. Their challenge is to connect with others and find value within themselves.",
    Sun: "There’s an unmistakably regal air to Solar Leos. These are dignified–even noble–folk. Leos have a reputation for being conceited, but think again. Leos do feel important, but this generally takes the form of wanting to change the world in some way–to make the world a better place. They are generally motivated by affection for people.",
    Moon: "Lunar Leos often feel a need to organize, and even control, their families and friends. They have an inner mission to set things right, and generally like to oversee the goings-on in their little circle.",
    Mercury: "When Mercury in Leo people speak, they do it with authority. Some of them come across as know-it-alls, but the more mature ones speak with style. They want others to know about their presence of mind and their know-how.",
    Venus: "Venus in Leo loves to court and be courted, and they need to feel very special. They are warm, generous, and even grand. Though really quite loyal to their partners (remember that love is THE most important thing in Leo’s life), they thrive on romantic attention.",
    Mars: "This position of Mars gives a drive for significance. Mars in Leo individuals possess a strong need to create in some way and they are determined that their lives  have not only meaning, but significant meaning!"
  },
  Virgo: {
    Uranus: "This placement provides a strong intuition and will be financially succesful, enjoying working in the public eye.",
    Pluto: "Pluto stays in a sign for 14-30 years, meaning its effects are generational like Uranus and Neptune. People with Pluto in Virgo are about working within systems to create methodological change.",
    Jupiter: "Being helpful, honest, orderly, and detail oriented are natural for someone with this placement. Practical and technical knowledge and skills are most valued.",
    Saturn: "Virgo Saturn shuns the limelight. Shy and reserved, they are timid in public. They may have obsessive compulsive traits or fears to deal with. Routine and order are important components in their lives. They may get so caught up in the details, however that they lose sight of the big picture.",
    Sun: "Virgo people are generally respectable, hard-working individuals who have a love of knowledge and know-how.Virgo’s symbol, the Virgin, shows itself in the lives of Virgos through a love of all that is “natural” and a certain purity of spirit that keeps Virgos self-sufficient and self-contained, at least on the surface.",
    Moon: "Lunar Virgos find security in the little things in life. They feel most content when they’ve straightened out all the details of everyday life.",
    Mercury: "Mercury in Virgo people are rarely flashy in their communication style, but they do thoroughly appreciate it when others acknowledge their brainpower. These people love to keep track of all the details.",
    Venus: "Venus in Virgo people are not the flirtatious sort. Instead, their appeal lies in their dedication, their willingness to work on the relationship, and to make the relationship work in real terms.",
    Mars: "Most Mars in Virgo natives are not particularly aggressive by nature. Although they can be a little hard-nosed and critical at times, they rarely resort to pushing others around. Still, an annoyed Mars in Virgo native can be difficult to be around!",
  },
  Libra: {
    Uranus: "People with Uranus in Libra find themseles in unusual relationships and don't follow traditional rules.",
    Sun: "Libra natives are generally thought to be sociable, somewhat intellectual souls. They have an almost innocent way about them that makes them very approachable. Generally quite eager to cooperate, Librans spend a lot of their time trying not to rock the boat.",
    Pluto: "Pluto stays in a sign for 14-30 years, meaning its effects are generational like Uranus and Neptune. People with Pluto in Libra are all about restoring peace and balance on a societal level.",
    Jupiter: "Jupiter in Libra loves people, and this will bring them much good fortune. Their natural diplomacy lets them interact with others and solve problems. If they can develop a strong sense of self, their luck grows stronger. This allows them to care less what others think of them.",
    Saturn: "Saturn in Libra must learn how to relate to other people on a personal and social level. They need to take responsibility for their actions in relationships. It lies entirely in their hands whether a relationship will be the source of growth or suffering. If they are receptive, reliable, tactful and organized, they could gain status and wealth.",
    Moon: "Moon in Libra people have a strong need for partnership. Without someone to share their lives with, they feel utterly incomplete. This is why many people with this position get involved in marriages or living-together arrangements quite young.",
    Mercury: "Libra communicators come across as very pleasing. Diplomacy comes naturally to these natives. At the very least, they take many pains to be diplomatic.",
    Venus: "Venus in Libra people will try to impress you with their kindness, evenhandedness, and willingness to make your relationship work. They have a polished manner in love, which sometimes makes them appear insincere or superficial. They are gentle lovers who hate to be offended.",
    Mars: "Mars in Libra natives often reflect about things before they act. Decisiveness is not their strong point, but they do, eventually, get things done. Many people with this position procrastinate, generally because they feel the need to weigh all of the alternatives before taking action.",
  },
  Scorpio: {
    Sun: "Scorpio isn’t afraid of getting their hands (their bodies, their minds) dirty. The darker side of life intrigues them, and they’re always ready to investigate.",
    Pluto: "Pluto stays in a sign for 14-30 years, meaning its effects are generational like Uranus and Neptune. People with Pluto in Scorpio are set on bringing things that have been hidden to light.",
    Neptune: "Neptune's effects are felt generationally. Generations with Neptune in Scorpio are prone to indulging in either transformation or degerneation through intense spiritual processes.",
    Uranus: "Uranus in Scorpio is forceful and determined, overcoming any obstacles that may come in their path.",
    Jupiter: "Jupiter in Scorpio can be very secretive and serious. They have a critical sense of judgment and a shrewd business sense. They are willing to dig down and get to the heart of a project, and this helps them succeed.",
    Saturn: "Saturn in Scorpio is impatient. They demand a lot from themselves and from those around them. They can be so intense that it can be overwhelming to those who are not as directed as they are. Full of willpower and energy, they are so determined to meet their goals it is hard for them to remain calm.",
    Moon: "While others may find security and comfort in material things, Moon in Scorpio people seek out emotional intensity. No matter what, there is something very intense about Lunar Scorpios. Their ability to see what isn’t obvious to the rest of the world can be intimidating or wildly attractive, depending on the audience.",
    Mercury: "These people are on an eternal quest to get to the very heart of any matter. This appears in anything that requires thought, and in almost every conversation they have.",
    Venus: "Venus in Scorpio people attract others with their intensity and willingness to commit. They have a strong and concentrated manner which suggests their feelings run deep. Their actions in love tend to promise deep commitment and sexual pleasure, even if they are not telling you this directly.",
    Mars: "Mars in Scorpio natives love to challenge themselves to do the impossible. They throw themselves into what they decide to do with concentrated energy and awesome willpower.",
  },
  Sagittarius: {
    Sun: "Sagittarians have an often blind faith in people, and in the world. Their optimism is infectious, although it can get them into trouble from time to time. These are curious people who love to learn. Their idealistic nature is hard to miss.",
    Neptune: "Neptune's effects are felt generationally. Generations with Neptune in Sagittarius prefer simple, black and white answers and are blinded by ideals.",
    Uranus: "Sagittarius Uranus loves science and philosophy. They love to keep abreast of the latest discoveries. They don't like conventional thinking; they like to start anew. They are not afraid to put themselves in danger to seek knowledge.",
    Jupiter: "Jupiter in Sagittarius finds that travel not only broadens the mind, it opens up doors of knowledge they may only have dreamed of. They are truly born under a lucky star, since this is Jupiter's natural home. It seems they can do no wrong.",
    Saturn: "Sagittarius Saturn is conservative, and they change only with much resistance. They may be very narrow-minded when it comes to philosophy or religion. With Saturn in Sagittarius, it gains structure and goals. They love to learn and now they have the focus they need. Alternatively, they can also develop tunnel vision.",
    Moon: "More than anything, Lunar Sagittarians have a need for personal freedom and space. They are extraordinarily happy and easygoing folk, as long as they don’t feel caged in or cooped up.",
    Mercury: "Freedom of thought is what Mercury in Sagittarius strives for — at least in theory. These people communicate in an optimistic, forward-looking manner. Their ideas are generally very big, but it’s probably wise to use tact when you see all the little holes in their arguments.",
    Venus: "When Venus in Sagittarius people are in love, they need to feel they can grow and expand their horizons through their relationship. They want to learn new things, and experience everything together. These are idealistic lovers who want you to appreciate their beliefs, visions, and ideals.",
    Mars: "When Mars in Sagittarius people get angry, they feel like running. They have to do something–not about it, but something else altogether. They don’t have a lot of patience to wait things out.",
  },
  Capricorn: {
    Sun: "Those with Sun in Capricorn have a realistic, grounded approach to life that can be seen no matter how dreamy the rest of the birth chart suggests. These people know how to do things, and to get things done.",
    Neptune: "Neptune's effects are felt generationally. Generations with Neptune in Capricorn experience a world that idealizes organization and bureacracy.",
    Uranus: "Capricorn Uranus is responsible and is capable of handling power with ease. They are good people to hold a job needing the trust of the public. They have the talent to see the coming trends long in advance.",
    Jupiter: "Jupiter in Capricorn has a strong drive for power, status, dignity and importance. By working hard and through determination, they often find themselves at the pinnacle of industrial, commercial or political success. They often gain in wealth as a side effect, though Capricorn Jupiter may find something tragic in being wealthy.",
    Saturn: "Saturn in Capricorn is very cautious and detail-oriented. They can be very charming or persistent when they want something. They are gifted with persuasion, and may make an effective speaker. They are fair and impartial. They have great foresight, and are gifted with practical matters. Some will be concerned with developing prestige. They have a strong sense of duty, but don't always find joy in accomplishing their task. They may find fulfillment in service to others.",
    Moon: "Being useful and productive are basic needs for Lunar Capricorns. Because they generally keep their emotions under check, Moon in Capricorn people come across as competent people.",
    Mercury: "With Mercury in Capricorn, natives have a strong need to compartmentalize the impressions they get from the world. These people often speak and write in a slow and methodical manner. They appreciate structure and order.",
    Venus: "Venus in Capricorn people will try to win your heart by displaying self-control, presence of mind, and responsible behavior. These lovers want you to know they are goal-oriented, witty, savvy, and controlled. Nobody can get the best of them.",
    Mars: "With fiery Mars in the more orderly sign of Capricorn, natives with this position have a subdued and controlled style of approaching life. Most don’t come across as particularly enthusiastic; rather, theirs is a low-key but determined energy.",
  },
  Aquarius: {
    Sun: "One of the standout characteristics of those born under the Sun Sign of Aquarius is their unwillingness to follow the beaten track. With advancement and progress on their minds, there can be an irreverence to old and outdated ways of thinking and doing things.",
    Neptune: "Neptune's effects are felt generationally. Generations with Neptune in Aquarius experience a social atmosphere of hightened intellect and unconventional connectivity.",
    Uranus: "Aquarius Uranus likes to socialize, and they are naturals at networking. They love to be where the action is. Highly inventive, they can envision what will happen down the road. They can understand complicated social problems and come up with ideas to help ease them.",
    Jupiter: "Luck finds Jupiter in Aquarius through their use of visionary ideals and innovative ideas. They can seek more luck by putting themselves in situations that place value on innovation and original thinking. To gather even more good fortune, Aquarius Jupiter needs to learn to compromise.",
    Saturn: "Saturn in Aquarius needs structure in their life, but it will be unconventional. They need a place to share their ideas, even when they are impractical or fanciful. Their big challenge is to grow while being open and fair to everyone. They can be strong, impersonal and scientific, or cold, unloving and opinionated. They may resent being told what they don't want to hear.",
    Moon: "Moon in Aquarius people are extremely observant. They are lifetime students of human nature, loving to analyze why people do what they do. This often stems from a detached–even shy–personality, especially in youth.",
    Mercury: "Unconventional in self-expression, Mercury in Aquarius natives enjoy breaking the rules. They are not necessarily loud or flamboyant people, but they often have a quiet way of stirring others up. These natives delight in exposing what they deem biases in others’ way of thinking.",
    Venus: "Venus in Aquarius people try to impress you with their open-minded, future-thinking spirit. They want you to see them as unique, rebellious, and a little provocative. They are attractive when they are acting a little aloof.",
    Mars: "The tried-and-true methods of getting things done are far too boring for those born with Mars in this unique and original sign. Mars in Aquarius natives often have a rather original view of the world as well.",
  },
  Pisces: {
    Sun: "Sun in Pisces people are frequently pegged as wishy-washy, but this is all a matter of opinion. What you will find behind a vaguely directionless, spacey manner is a deep person with real dreams.",
    Neptune: "Neptune's effects are felt generationally. Generations with Neptune in see ego dissipation and a desire to see social unity.",
    Uranus: "Pisces Uranus likes fantasy and mysticism. They can be responsible for changes in religion, beliefs or morals. They have an inner wisdom if they allow it to be heard.",
    Jupiter: "Jupiter in Pisces is content to remain behind the scenes to help. They don't seek the spotlight. They are very sensitive, but easy going. They may not be very ambitious. They don't need a lot of material things to be content in life. They may closely follow a religion or mystical practices. They may be prone to being taken advantage of due to their compassionate nature. They like seclusion.",
    Saturn: "The life lesson for Saturn in Pisces is to grow in emotional understanding, humility and compassion. They feel obligated to help those less fortunate than themselves. They may need to overcome negative emotions, deep fears and a wandering imagination. They are adept in the fields of social work, medical care, teaching, religion and the arts.",
    Moon: "Lunar Pisceans are known to be dreamy and not always in touch with reality. However, though these people may not always show real-world savvy in day-to-day, practical affairs, they make up for this with remarkable intuition.",
    Mercury: "Mercury in Pisces are gentle communicators with a soft touch that is pleasing and warm. Some of them come across in an almost poetic way. Not given to bother too much with details, these individuals tend to sponge up the feelings and moods of their environment.",
    Venus: "Venus in Pisces people project themselves as dreamy, soft-hearted partners. Everything about the way they flirt promises a lovely time. Theirs is an elusive charm — they are sweetly playful, a little moody, and perhaps a little irregular.",
    Mars: "Mild-tempered and gentle, these guys and gals move through life in a manner that can hardly be considered direct. Mars is the planet of action and assertion, and Pisces is a passive sign that rarely asserts itself in a direct fashion.",
  }
}
